### ISSUE TITLE
Get My Projects API retrieves all the projects though logged user is not participant of the projects 

### ISSUE THREAD

**Issue by ankita1286** [iTwin/projects-client#16] opened 2022-04-27 09:41 UTC
Get My Projects API retrieves all the projects though logged user is not participant of the projects 
https://api.bentley.com/projects
Is there anything else that needs to be provided to API apart from token

**Comment by davidhjones** [comment] 2022-06-23 15:29
This seems to be a duplicate of #15

**Comment by calebmshafer** [comment] 2023-02-08 01:09
closing as a duplicate

**Closed by calebmshafer** 2023-02-08 01:09 UTC
